### ISSUE TITLE
Fails after getting one moment

### ISSUE THREAD

**Issue by jasonsnyder** [rrrkren/topshot-sales#1]
Thanks for making this example. I'm running through your medium post and I'm stuck. At first I was only getting the block height with no moments. Now I'm just getting an error after it finds the first moment. Any thoughts?

```
$ go run main.go
current height:  11124015
moment purchased: momentid: 992820, price: 3.000000, seller: 0553190951a432a6
panic: error fetching sale moment from flow: client: rpc error: code = Internal desc = failed to execute the script on the execution node: rpc error: code = Internal desc = failed to execute script: failed to execute script (internal error): error getting register (account_address_state) value at 0a534eed0ce8eeee1fa330e7f5aff33ee68a6c954947ab330316366d22e1362b: trie with the given rootHash [0a534eed0ce8eeee1fa330e7f5aff33ee68a6c954947ab330316366d22e1362b] not found

goroutine 1 [running]:
main.handleErr(...)
	/Users/jsnyder/topshot/topshot-sales-master/main.go:14
main.main()
	/Users/jsnyder/topshot/topshot-sales-master/main.go:44 +0x7db
exit status 2
```

**Comment by jasonsnyder** [comment]
Never mind. It's working now.

**Comment by rrrkren** [comment]
This is actually a flow issue. The team is aware and will fix at some point

**Comment by rrrkren** [comment]
Thanks for the issue!

**Comment by jasonsnyder** [comment]
Cool Thanks for the update. Yeah it was working for a bit yesterday and now the error is back. Is there a way to avoid the error or is this just stuck until they fix the flow issue?

**Comment by natron34** [comment]
@jasonsnyder did it resolve itself? 

@rrrkren  does it have something do with the network being down?

**Comment by jasonsnyder** [comment]
Yeah seems to have resolved itself. Haven't seen it in a couple days.

**Comment by bigoper** [comment]
Hi @jasonsnyder @nathanchiu34,

I'm facing the same issue here.
```js
rpc error: code = Internal desc = failed to execute the script on the execution node execution-
4ab025ab974e7ad7f344fbd16e5fbcb17fb8769fc8849b9d241ae518787695bd@execution-
003.mainnet5.nodes.onflow.org:3569=1000: rpc error: code = Internal desc = failed to execute script: failed to execute script 
(internal error): ledger returns unsuccessful: error getting register (account_address_state) value at 
6d8849e9dbce8ef36a9ca74023050af2c90db50d7683f8017b47db7baafa0d8d: trie with the given rootHash 
[6d8849e9dbce8ef36a9ca74023050af2c90db50d7683f8017b47db7baafa0d8d] not found
```

- I was wondering if you've found way to resolve this?

Thanks!

**Comment by jasonsnyder** [comment]
Sorry no clue what causes it, and it seems to go away and come back. I'm assuming this is a flow issue as @rrrkren has commented and is probably just low on the priority list.
