### ISSUE TITLE
Live market scraper

### ISSUE THREAD

**Issue by Ng2k** [rrrkren/topshot-sales#2]
### THE GOAL

I'm trying to build a live market scraper on top of this project

### THE PROBLEM

This project only search for the event "MomentPurchased" and your function GetSaleMomentFromOwnerAtBlock() retrieves all the token properties, such as setName, playName etc...

I'm not searching for the event "MomentPurchased" but "MomentListed". I'm new to this technology, sorry for the lack of knowledge, but what changes I need to do to GetSaleMomentFromOwnerAtBlock() in order to make it works also in this scenario?

Right now I have all the events "MomentListed", but I don't really know how to get the tokens informations from that. I have the tokenID, price and seller address (from the event), but I don't know how to change this function.

There is a way to do that?

Right now my naive solution is: just change the event type. But I think that also the cadence needs to change.

### ERROR

the error I have is:
```
error fetching sale moment from flow: client: rpc error: code = Unknown desc = 3 errors occurred:
* rpc error: code = Internal desc = failed to execute the script on the execution node execution-160241f88cbfaa0f361cf64adb0a1c9fc19dec1daf4b96550cd67b7a9fb26cd9@execution-002.mainnet4.nodes.onflow.org:3569=1000: rpc error: code = Internal desc = failed to execute script: failed to execute script (internal error): error getting register (account_address_state) value at e24eb40d7d6aa154ddc8421097aa17964ddb85646fc83237aae4e31bd052b0ec: trie with 
the given rootHash [e24eb40d7d6aa154ddc8421097aa17964ddb85646fc83237aae4e31bd052b0ec] not found
```

Thanks for the time

**Comment by Nhandos** [comment]
I've been getting the same error as well. It seems to happen periodically and has nothing to do with the source code

```
current height:  11412702
moment purchased: momentid: 1830221, price: 6.000000, seller: 6b69566d878839db
panic: error fetching sale moment from flow: client: rpc error: code = Unknown desc = 3 errors occurred:
        * rpc error: code = Internal desc = failed to execute the script on the execution node execution-160241f88cbfaa0f361cf64adb0a1c9fc19dec1daf4b96550cd67b7a9fb26cd9@execution-002.mainnet4.nodes.onflow.org:3569=1000: rpc error: code = Internal desc = failed to execute script: failed to execute script (internal error): error getting register (account_address_state) value at 4331f5bad2b527e2b3bed352eee99c9a35436716682df32ed2952d361dda9ebb: trie with the given rootHash [4331f5bad2b527e2b3bed352eee99c9a35436716682df32ed2952d361dda9ebb] not found
        * rpc error: code = Internal desc = failed to execute the script on the execution node execution-9686399a8a5418a12e762cfaeff2ea348c2137f554560917760e0d47acf2cda4@execution-001.mainnet4.nodes.onflow.org:3569=1000: rpc error: code = Internal desc = failed to execute script: failed to execute script (internal error): error getting register (account_address_state) value at 4331f5bad2b527e2b3bed352eee99c9a35436716682df32ed2952d361dda9ebb: trie with the given rootHash [4331f5bad2b527e2b3bed352eee99c9a35436716682df32ed2952d361dda9ebb] not found
        * rpc error: code = Internal desc = failed to execute the script on the execution node execution-4ab025ab974e7ad7f344fbd16e5fbcb17fb8769fc8849b9d241ae518787695bd@execution-003.mainnet4.nodes.onflow.org:3569=1000: rpc error: code = Internal desc = failed to execute script: failed to execute script (internal error): error getting register (account_address_state) value at 4331f5bad2b527e2b3bed352eee99c9a35436716682df32ed2952d361dda9ebb: trie with the given rootHash [4331f5bad2b527e2b3bed352eee99c9a35436716682df32ed2952d361dda9ebb] not found
```

**Comment by Ng2k** [comment]
But I can't undestand why everything works the second after I change the event type back to "MomentPurchased". Both of them (MomentPurchased and MomentListed) have the same params (tokenID, price and seller address). So why there is such an error?

How can I change the cadence code in order to work in this case?

**Comment by henkgaming** [comment]
Hi guys; 

I also get this error. When I look at the function GetSaleMomentFromOwnerAtBlock an apostrophe is used. Do any of you know the function of this apostrophe? 
Kinda looks like a typo to me but it probably isn't.. Thanks in advance!

**Comment by Nhandos** [comment]
> But I can't undestand why everything works the second after I change the event type back to "MomentPurchased". Both of them (MomentPurchased and MomentListed) have the same params (tokenID, price and seller address). So why there is such an error?
> 
> How can I change the cadence code in order to work in this case?

I can change mine from MomentPurchased to MomentListed without any problem. It's when I try to run the function `GetSaleMomentFromOwnerAtBlock` that I get that error.

You can use this link to check the contract that's deployed on flow mainnet. I find it helpful just to confirm that the contract has the same function parameters as the ones in https://github.com/dapperlabs/nba-smart-contracts

https://flow-view-source.com/mainnet/account/0x0b2a3299cc857e29

**Comment by Ng2k** [comment]
@Nhandos, I've coded a [web server](https://github.com/Ng2k/nbatopshot-LiveMarketScraper), but using [flow-js-sdk](https://github.com/onflow/flow-js-sdk).

I used **javascript** and **nodejs** as you can see, not go.

It's a web scraper for all the events "MomentListed" (excluding the MomentListed already purchased). I've just finished this first version, so it's not perfect (for example it displays only the all the events from the least 50 blocks, because there is too much data to process so it's not so fast).

If you're interested you can take a look (naturally you need to install nodejs)

Right now I'm trying to speed up the program in order to analyze more blocks and also trying to create a queue with all the token on sale, not just displaying only events from 50 blocks.

**Comment by Nhandos** [comment]
Nice!!! Is it anything similar to the features in 
https://cryptoslam.io/nba-top-shot ?

I am interested in a way to see trade historical data such as volume/price floor for any given top shot-moments. I don't think Cryptoslam has that features yet but I believe it's in the works according the some people on the Topshot discord

**Comment by Ng2k** [comment]
Right now it has a table with:

- Full Name of the player
- Season
- Set Name
- Price

![liveMarket](https://user-images.githubusercontent.com/18485072/106382225-74d53d00-63be-11eb-80f0-22ccbc8aea86.png)

But I'm planning to improve the processing time in order to analyze more blocks and also trying to create a queue and not just displaying the last 50 blocks every refresh.

If you are interested you can take a look and also trying to make some pull requests

**Comment by rrrkren** [comment]
hi friends! sorry I've been slammed for the past little while. 
the `Internal` error you see `trie with 
the given rootHash [e24eb40d7d6aa154ddc8421097aa17964ddb85646fc83237aae4e31bd052b0ec] not found` has to do with how flow archives old data to make room for newer ones, so ExecuteScriptAtBlockHeight won't always work at a previous block when there are high traffic on the network even though you might be trying to run it on a very recent one. 
I've also setup discussion board for this repo so if you have any questions feel free to ask [there](https://github.com/rrrkren/topshot-sales/discussions) as well. 
@Ng2k thanks for sharing it looks great! feel free to also look into my other FCL project for some inspirations. https://github.com/rrrkren/topshot-explorer

**Comment by Ng2k** [comment]
Hi @rrrkren , thanks for the response. This problem doesn't show up with the js sdk (I think), because I've never seen such an error in my project. Maybe it's due to the function implementation in go and javascript, I don't know. 

Right now I'm thinking how I can improve the way I display the data and also how I can analyze more blocks than 50 without waiting 1 hour (maybe some kind of parallelism or more asynchronous code).
